---
pdf_document: default
author: "Loïc Pages & Eric Imbert"
date: "`r Sys.Date()`"
output:
  html_document: null
  df_print: paged
  pdf_document: default
word_document: default
title: "Comparisons between observed/predicted distributions for size and age using global IPM"
---

```{r setup, include=FALSE}
rm(list=ls())
#library(spaMM)
library(tidyverse)
library(popbio)
library(dplyr)
#library(splines)


observed_data_raw <- read.csv("../data/donneesIPM.csv")
observed_data <- observed_data_raw

AgeMax <- 8
observed_data$Age[observed_data$Age > AgeMax] <- AgeMax
observed_data <- observed_data[!is.na(observed_data$Size0Mars) & !is.na(observed_data$Age),]

MatrixDim <- 50
load("../IPM/VitalRates.RData")
load("../IPM/Global_IPM.RData")


annees <- 1995:2021
populations <- c("Po","Au","Pe","E1","E2","Cr")

flr0 <- function(x, a, Beta=0) {
  fake_data <- expand.grid(
  year = annees,
  Pop = populations,
  Size0Mars = unique(x),
  Age = a)
  predi <- plogis(predict(Flowering, newdata = fake_data, allow.new.levels = T, type = "link") + Beta) 
  meanpredi <- aggregate(predi, list(fake_data$Size0Mars), mean)
  return(meanpredi$V1)
}

n.size <- MatrixDim
minsize <-  0.5
maxsize <-  25
maxsize1 <- 15
h <-  (maxsize - minsize) / n.size
h1 <-  (maxsize1 - minsize) / n.size
b <- minsize + c(0:n.size) * h
ymid.a = 0.5 * (b[1:n.size] + b[2:(n.size + 1)])
yI.a <- matrix(nrow = n.size, ncol = 2)
for (i in 1:n.size) {
  yI.a[i, 1] <- b[i]
  yI.a[i, 2] <- b[i + 1]
}

b1 = minsize + c(0:n.size) * h1
ymid.1 = 0.5 * (b1[1:n.size] + b1[2:(n.size + 1)])
yI.1 <- matrix(nrow = n.size, ncol = 2)
for (i in 1:n.size) {
  yI.1[i, 1] <- b1[i]
  yI.1[i, 2] <- b1[i + 1]
}


```

Stable distribution Size and Age

```{r}
A <- eigen.analysis(Global_IPM)


AA <- data.frame(
  Size1 = rep(ymid.1,AgeMax),
  Size = rep(ymid.a,AgeMax),
  density = rep(NA,MatrixDim*AgeMax),
  age = rep(NA,MatrixDim*AgeMax)
)
  
for (i in 1:AgeMax){
  AA$density[(MatrixDim*(i-1)+1):(MatrixDim*i)] <- A$stable.stage[(MatrixDim*(i-1)+1):(MatrixDim*i)]
  AA$age[(MatrixDim*(i-1)+1):(MatrixDim*i)]  <- rep(i,MatrixDim)
}

N <- matrix(ncol = AgeMax, nrow = MatrixDim)
for (i in 1:AgeMax){
  N[,i] <- A$stable.stage[(MatrixDim*(i-1)+1):(MatrixDim*i)]
}
W <- function(age){
  return(N[(MatrixDim*(age-1)+1):(MatrixDim*age)])
}

```

Histogramme de tailles observées

```{r}
hist_data_list <- list()

# Boucle sur les ages
for (a in 1:AgeMax) {
  data_age <- observed_data %>% filter(Age == a)
  if (a == 1) {
    bins <- b1
    mids <- ymid.1
  } else {
    bins <- b
    mids <- ymid.a
  }
  hist_counts <- hist(data_age$Size0Mars, breaks = bins, plot = FALSE)
  df_hist <- data.frame(
    Age = a,
    x = mids,
    count = hist_counts$counts
  )
  hist_data_list[[a]] <- df_hist
}

# Combine tout
hist_data <- bind_rows(hist_data_list)

# Normalisation
N_total <- sum(hist_data$count)
hist_data <- hist_data %>%
  mutate(prob = count / N_total,
         age=Age)
```

Distribution for observed/predicted size for each age

```{r, warning=FALSE}
AA %>% 
  ggplot()+
  geom_col(data=hist_data,aes(x = x, y = prob), fill = "steelblue", color = "black", width = h) +
  geom_line(aes(x=Size,y=density),col="red")+
  # geom_smooth(aes(x=Size,y=density))+
  theme_bw()+
  facet_wrap(~age,scale="free")+
  labs(x="Size (cm)",
      y="Density",
      subtitle = "Histogram : observed distribution
      Red line = predicted distribution")
```

Distribution for observed/predicted age

```{r}
age_dist <- hist_data %>%
  group_by(age) %>% 
  summarize(prob = sum(prob))

AA %>% group_by(age) %>% 
  summarize(density = sum(density)) %>% 
  ggplot()+
  geom_col(data=age_dist, aes(x = age, y = prob, fill = as.factor(age)), color = "black", width = 0.5, show.legend = FALSE) +
  scale_fill_brewer(palette = "Spectral", direction = -1) +
  geom_line(aes(y=density,x=age),col="red",linewidth=1)+
  theme_bw()+
  labs(x="Age",
       y="Density",
       subtitle = "Bar :observed distribution
       Red line : predicted distribution ")

```

Age at flowering

```{r}
hist(
  observed_data_raw$Age[observed_data_raw$Flowering == 1],
  breaks = seq(0.5, 12.5, by = 1),
  xaxt = "n",
  xlab = "Age",
  ylab = "Number of flowering plants",
  main = "Raw data")
axis(1, at = 1:12, labels = 1:12)

hist(
  observed_data$Age[observed_data$Flowering == 1],
  breaks = seq(0.5, 12.5, by = 1),
  xaxt = "n",
  xlab = "Age",
  ylab = "Number of flowering plants",
  main = "AgeMax = 8")
axis(1, at = 1:12, labels = 1:12)

#Observed mean age and SD
obs_age <- mean(observed_data$Age[observed_data$Flowering==1],na.rm = T)
obs_sd_age <- sd(observed_data$Age[observed_data$Flowering==1], na.rm = T)

#Predicted mean age and SD
mu_a <- sum(W(1)*flr0(ymid.1,1,0))
mu2 <- mu_a2 <- sum(W(1)*flr0(ymid.1,1,0))
for(a in 2:AgeMax){
  mu_a <- mu_a + sum(a*W(a)*flr0(ymid.a,a,0))
  mu_a2 <- mu_a2 + a^2 * sum(W(a)*flr0(ymid.a,a,0))
  mu2 <- mu2 + sum(W(a)*flr0(ymid.a,a,0))
}

pred_age <- mu_a/mu2
sd_age   <- sqrt(mu_a2/mu2 - pred_age^2)
```


Distribution of size for flowering plants

```{r, warning=FALSE}
#Proportion de plantes en fleurs dans la population
Flr_dens <- sum(flr0(ymid.1,1)*W(1))
for (a in 2:AgeMax) { 
  Flr_dens <- Flr_dens + sum(flr0(ymid.a, a) * W(a))
}

Flry <- rep(NA, MatrixDim) #Distribution de taille des plantes en fleur
Z <- rep(NA, MatrixDim)
for (i in 1:MatrixDim) {
  Flry[i] <- sum(flr0(ymid.1[i],1)*W(1)[i])
  for (a in 2:AgeMax) {
    Flry[i] <- Flry[i] + flr0(ymid.a[i], a) * W(a)[i]
  }
}
Z <- Flry/Flr_dens #normalisation

flower_data <- observed_data[observed_data$Flowering==1 & !is.na(observed_data$Flowering),]
flower_data <- flower_data %>%
  group_by(Size0Mars) %>%
  summarise(n_fleuri = n()) %>%
  mutate(Wobs = n_fleuri / sum(n_fleuri),
         Size=Size0Mars) %>% dplyr::select(!n_fleuri) %>% 
  dplyr::select(!Size0Mars)

#Observed mean size and SD
size_n <- nrow(observed_data[observed_data$Flowering==1 & !is.na(observed_data$Flowering),])
obs_mean <- sum (flower_data$Wobs*flower_data$Size)
sd_obs <- sqrt (sum (flower_data$Wobs * (flower_data$Size - obs_mean)^2))
obsCI_low <- obs_mean-1.96*sd_obs/sqrt(size_n)
obsCI_high <- obs_mean+1.96*sd_obs/sqrt(size_n)

#Predicted mean size and SD
pred_mean <- sum (Z*seq(0.5,25,0.5))
sd_pred <- sqrt (sum (Z * (seq(0.5,25,0.5) - pred_mean)^2))
predCI_low <- pred_mean-1.96*sd_pred/sqrt(size_n)
predCI_high <- pred_mean+1.96*sd_pred/sqrt(size_n)

tibble(Size = seq(0.5,25,0.5),
                 West = Z) %>% 
  left_join(flower_data,join_by(Size)) %>% 

  ggplot(aes(x = Size)) +
  geom_bar(aes(y = Wobs), stat = "identity", fill = "steelblue",color="black") +
  geom_line(aes(y = West), color = "red", linewidth = 1) +
  labs(x = "Size at flowering", y = "Density",
       subtitle = "Histogram : observed distribution
       Red line : predicted distribution") +
  theme_bw()+
      theme(
    axis.title.x = element_text(size = 16),  # Taille du titre axe X
    axis.title.y = element_text(size = 16),  # Taille du titre axe Y
    axis.text.x = element_text(size = 14),   # Taille des graduations axe X
    axis.text.y = element_text(size = 14)    # Taille des graduations axe Y
  )





```



Mean size and mean age at flowering per population

```{r}

load("../IPM/IPM_Kernal_Pop.RData")

mean_size_age <- data.frame (populations, pred_size=NA,pred_age=NA,
                             obs_size=NA, se_size=NA,
                             obs_age=NA,se_age=NA)

flr0 <- function(x, a, Pop, Beta=0) {
  fake_data <- expand.grid(
  year = annees,
  Pop = Pop,
  Size0Mars = unique(x),
  Age = a)
  predi <- plogis(predict(Flowering, newdata = fake_data, allow.new.levels = T, type = "link") + Beta) 
  meanpredi <- aggregate(predi, list(fake_data$Size0Mars), mean)
  return(meanpredi$V1)
}


for (mypop in 1:6) {
A <- eigen.analysis(IPMKernal_Pop[[mypop]])
N <- matrix(ncol = AgeMax, nrow = MatrixDim)
for (i in 1:AgeMax){
  N[,i] <- A$stable.stage[(MatrixDim*(i-1)+1):(MatrixDim*i)]
}
W <- function(age){
  return(N[(MatrixDim*(age-1)+1):(MatrixDim*age)])
}

mu_size <- sum(ymid.1*W(1)*flr0(ymid.1,1, populations[mypop]))
mu_a <- sum(W(1)*flr0(ymid.1,1, populations[mypop]))
mu2 <- sum(W(1)*flr0(ymid.1,1, populations[mypop]))
for(a in 2:AgeMax){
  mu_size <- mu_size + sum(ymid.a*W(a)*flr0(ymid.a,a, populations[mypop]))
  mu_a <- mu_a + sum(a*W(a)*flr0(ymid.a,a, populations[mypop]))
  mu2 <- mu2 + sum(W(a)*flr0(ymid.a,a, populations[mypop]))
}
mean_size_age$pred_size[mypop] <- mu_size/mu2
mean_size_age$pred_age [mypop] <- mu_a/mu2

rer <- observed_data[observed_data$Pop==populations[mypop],]
mean_size_age$obs_size[mypop] <- mean(rer$Size0Mars[rer$Flowering==1])
mean_size_age$se_size[mypop] <- sd(rer$Size0Mars[rer$Flowering==1])

mean_size_age$obs_age[mypop] <- mean(rer$Age[rer$Flowering==1])
mean_size_age$se_age[mypop] <- sd(rer$Age[rer$Flowering==1])
}

ggplot(data=observed_data[observed_data$Flowering==1,],aes(x=Pop, y=Age))+
    geom_boxplot() +
  geom_point(data=mean_size_age, aes(x=populations, y=pred_age), col="red", shape=20, size=3) +
     theme_bw()

ggplot(data=observed_data[observed_data$Flowering==1,],aes(x=Pop, y=Size0Mars))+
    geom_boxplot() +
  geom_point(data=mean_size_age, aes(x=populations, y=pred_size), col="red", shape=20, size=3) +
     theme_bw()
       

```

Figure for MS

```{r, warning=FALSE, echo=FALSE}
library(patchwork)



Figure2a <- AA %>% 
  ggplot()+
  geom_col(data=hist_data,aes(x = x, y = prob), fill = "steelblue", color = "black", width = h) +
  geom_line(aes(x=Size,y=density),col="red")+
  # geom_smooth(aes(x=Size,y=density))+
  theme_bw(base_size = 6)+
  facet_wrap(~age,scale="free")+
  labs(subtitle = "A- Size distributions according to age",
       x="Size (cm)",
      y="Density")


Figure2b <- tibble(Size = seq(0.5,25,0.5),
                 West = Z) %>% 
  left_join(flower_data,join_by(Size)) %>% 
  ggplot(aes(x = Size)) +
  geom_bar(aes(y = Wobs), stat = "identity", fill = "steelblue",color="black") +
  geom_line(aes(y = West), color = "red", linewidth = 0.5) +
  labs(x = "Size (cm)", y = "Density",
       subtitle = "B- Size at flowering") +
theme(axis.title.y = element_text(margin = margin(r = 5)))+
  theme_bw(base_size = 6)
  

Figure2c <- ggplot(data=observed_data[observed_data$Flowering==1,],aes(x=Pop, y=Size0Mars))+
    geom_boxplot() +
  geom_point(data=mean_size_age, aes(x=populations, y=pred_size), col="red", shape=20, size=1.5) +
  labs (x="Population",
        y= "Size (cm)",
        subtitle = "C- Mean size at flowering by population") +
  theme_bw(base_size = 6) +
   theme(axis.title.y = element_text(margin = margin(r = 5)))


Figure2d <- ggplot(data=observed_data[observed_data$Flowering==1,],aes(x=Pop, y=Age))+
    geom_boxplot() +
  geom_point(data=mean_size_age, aes(x=populations, y=pred_age), col="red", shape=20, size=1.5) +
  labs (x="Population",
        y= "Age (year)",
        subtitle = "D- Mean age at flowering by population") +
  theme_bw(base_size = 6) +
   theme(axis.title.y = element_text(margin = margin(r = 5)))



cairo_ps("Figure_2.ps", onefile=TRUE, width=8.27, height=11.69)
Figure2a + Figure2b + Figure2c + Figure2d +
plot_layout(ncol = 2, nrow=2)  

dev.off()

```


