---
title: "Comparisons IPM & MPM results"
author: "Loïc Pages & Eric Imbert"
date: "`r Sys.Date()`"
output:
  html_document:
  df_print: paged
word_document: default
pdf_document: default
---

```{r setup, include=FALSE}
library(popbio)
library(ggplot2)
library(tidyr)
MatrixDim <-50

```


Comparison of LAMBDA
```{r, echo=FALSE}
load("../IPM/Global_IPM.RData")
load("MPM/matrice_globale.Rdata")
print(paste("Asymptotic Growth rate from IPM= ",lambda(Global_IPM)))
print(paste("Asymptotic Growth rate from MPM= ",lambda(matrice_globale)))

rm(list=ls())

```


Lambda per year

```{r}
load("../IPM/IPM_Kernal_Year.RData")
load("MPM/matricesperyear.RData")

annees <- 1995:2021

GrowthRateIPM <- data.frame(annees, NA)
colnames(GrowthRateIPM)=c("Year", "Lambda")

GrowthRateMPM <- data.frame(annees, NA)
colnames(GrowthRateMPM)=c("Year", "Lambda")


for(i in 1:length(annees)) {
  GrowthRateIPM$Lambda[i] <- lambda(IPMKernal_Year[[i]])  
  GrowthRateMPM$Lambda[i] <- lambda(matrices[[i]])  
}

cor.test(GrowthRateIPM$Lambda, GrowthRateMPM$Lambda)

```

Comparisons of vital rates
Step 1 Vital rates as in the MPM


N1 : density of seedlings
N2 : density of rosetts (age >1 )
N3 : density of flowering plants  
  
  
Fecundity
$$
    fs_0=\frac{\sum\limits_{a=1}^8\sum\limits_i\sum\limits_j W_{a,j}\tilde{F}(j,a,i,1)}{\sum\limits_{a=1}^8\sum\limits_jW_{a,j}f(j,a)}
$$

Seedling survival
$$   s_1(1-\alpha_1)=\frac{\sum\limits_i\sum\limits_j W_{1,j}\tilde{P}(j,1,i,2)(1-f(i,2))}{\sum\limits_jW_{1,j}(1-f(j,1))}$$

Rosett survival
$$ s_2(1-\alpha_2)=\frac{\sum\limits_i\sum\limits_j \sum\limits_{a=2}^7W_{a,j}\tilde{P}(j,a,i,a+1)(1-f(i,a+1))+ W_{8,j}\tilde{P}(j,8,i,8)(1-f(i,8))}{\sum\limits_{a=2}^8\sum\limits_jW_{a,j}(1-f(j,a))}$$

Flowering stage
$$s_2\alpha_2=\frac{\sum\limits_i\sum\limits_j \sum\limits_{a=2}^7W_{a,j}\tilde{P}(j,a,i,a+1)f(i,a+1)+ W_{8,j}\tilde{P}(j,8,i,8)f(i,8)}{\sum\limits_{a=2}^8\sum\limits_jW_{a,j}(1-f(j,a))}$$



```{r}
VitalRatesIPM <- list()
Pop <- c("E2", "E1", "Au", "Po", "Pe", "Cr")
annees <- 1995:2021
minsize <-  0.5
maxsize <-  25
maxsize1 <- 15
n.size <- MatrixDim <- 50
h <-  (maxsize - minsize) / n.size
h1 <-  (maxsize1 - minsize) / n.size
b = minsize + c(0:n.size) * h

#sizes for an individual of age a
#midpoint
ymid.a = 0.5 * (b[1:n.size] + b[2:(n.size + 1)])
#intervals
#yI.a <- matrix(nrow = n.size, ncol = 2)
#for (i in 1:n.size){
#  yI.a[i,1] <- b[i]
#  yI.a[i,2] <- b[i+1]
#}

b1 = minsize + c(0:n.size) * h1
#sizes for an individual of age 1
#midpoint
ymid.1 = 0.5 * (b1[1:n.size] + b1[2:(n.size + 1)])

#intervals
#yI.1 <- matrix(nrow = n.size, ncol = 2)
#for (i in 1:n.size){
#  yI.1[i,1] <- b1[i]
#  yI.1[i,2] <- b1[i+1]
#}

load("../IPM/VitalRates.RData")

#Flowering function for The survival-growth kernel
flr0 <- function(x, a, Beta=0,Pop,year) {
  fake_data <- expand.grid(
  year = year,
  Pop = Pop,
  Size0Mars = unique(x),
  Age = a)
  predi <- plogis(predict(Flowering, newdata = fake_data, allow.new.levels = T, type = "link") + Beta)
  meanpredi <- aggregate(predi, list(fake_data$Size0Mars), mean)
  return(meanpredi$V1)
}

for (k in 1:length(annees)) {
  # Définition de la matrice, du vecteur propre et des autres fonctions associées
  year <- annees[k]
  M <- IPMKernal_Year[[k]]
  A <- eigen.analysis(M)
  N <- matrix(ncol = 8, nrow = 50)
  for (i in 1:8) {
    N[, i] <- A$stable.stage[(50 * (i - 1) + 1):(50 * i)]
  }
  V <- function(age) {
    return(N[(50 * (age - 1) + 1):(50 * age)])
  }
  Fec <- function(i, a) {
    #i indice de taille de plantule
    #a age de plante mère
    return(M[i, ((a - 1) * 50 + 1):(a * 50)])
  }
  P <- function(i, a) {
    #i indice de taille de plante à t+1
    #a age de plante à t
    if (a == 8) {
      return(M[((50 * (a - 1)) + i), ((a - 1) * 50 + 1):(a * 50)])
    }
    return(M[((50 * a) + i), ((a - 1) * 50 + 1):(a * 50)])
  }
#fecundity
N1t1 <- 0
  N3t0 <- sum(V(1) * flr0(ymid.1, 1, 0, Pop, year))
  for (a in 2:8) {
    N3t0 <- N3t0 + sum(V(a) * flr0(ymid.a, a, 0, Pop, year))
  }
  for (a in 1:8) {
    for (i in 1:MatrixDim) {
      N1t1 <- N1t1 + sum(Fec(i, a) * V(a))
    }
  }
  fs0 <- N1t1 / N3t0

#seedling survival  
  N2t1 <- 0
  N1t0 <- sum(V(1) * (1 - flr0(ymid.1, 1, 0, Pop, year)))
  for (i in 1:MatrixDim) {
    N2t1 <- N2t1 + sum(P(i, 1) * V(1) * (1 - flr0(ymid.a[i], 2, 0, Pop, year)))
  }
  s1_1a1 <- N2t1 / N1t0

#rosette survival  
  
    N2t1 <- 0
  N2t0 <- 0
  for (a in 2:8) {
    N2t0 <- N2t0 + sum(V(a) * (1 - flr0(ymid.a, a, 0, Pop, year)))
  }
  for (i in 1:MatrixDim) {
    for (a in 2:7) {
      N2t1 <- N2t1 + sum(P(i, a) * V(a) * (1 - flr0(ymid.a[i], a + 1, 0, Pop, year)))
    }
    N2t1 <- N2t1 + sum(P(i, 8) * V(8) * (1 - flr0(ymid.a[i], 8, 0, Pop, year)))
  }
  s2_1a2 <- N2t1 / N2t0

#flowering  
  N2t1 <- 0
  N2t0 <- 0
  for (a in 2:8) {
    N2t0 <- N2t0 + sum(V(a) * (1 - flr0(ymid.a, a, 0, Pop, year)))
  }
  for (i in 1:MatrixDim) {
    for (a in 2:7) {
      N2t1 <- N2t1 + sum(P(i, a) * V(a) * flr0(ymid.a[i], a + 1, 0, Pop, year))
    }
    N2t1 <- N2t1 + sum(P(i, 8) * V(8) * flr0(ymid.a[i], 8, 0, Pop, year))
  }
  s2_a2 <- N2t1 / N2t0
  #formation des nouvelles matrices
  VitalRatesIPM[[k]] <- matrix(c(0, s1_1a1, 0, 0, s2_1a2, s2_a2, fs0, 0, 0),
                         nrow = 3,
                         ncol = 3)
}

save(VitalRatesIPM, file = "Vitalrates_Year_from_IPM.RData")
```


Import data from MPM and make a graph for each vital rate

```{r}
lht <- expand.grid(Model = c("IPM","MPM"),
                   years = annees,
                   s1 = NA,
                   s2_1a2 = NA,
                   s2a2 = NA,
                   fs0 = NA,
                   s2 = NA,
                   a2 = NA)
lhtIPM <- lht[lht$Model=="IPM",]
lhtMPM <- lht[lht$Model=="MPM",]

for(i in 1:27){
  lhtIPM$s1[i] <- VitalRatesIPM[[i]][2,1]
  lhtIPM$s2_1a2[i] <- VitalRatesIPM[[i]][2,2]
  lhtIPM$s2a2[i] <- VitalRatesIPM[[i]][3,2]
  lhtIPM$fs0[i] <- VitalRatesIPM[[i]][1,3]
  lhtIPM$s2[i] <- VitalRatesIPM[[i]][2,2]+VitalRatesIPM[[i]][3,2]
  lhtIPM$a2[i] <- VitalRatesIPM[[i]][3,2]/(VitalRatesIPM[[i]][2,2]+VitalRatesIPM[[i]][3,2])
  lhtMPM$s1[i] <- matrices[[i]][2,1]
  lhtMPM$s2_1a2[i] <- matrices[[i]][2,2]
  lhtMPM$s2a2[i] <- matrices[[i]][3,2]
  lhtMPM$fs0[i] <- matrices[[i]][1,3]
  lhtMPM$s2[i] <- matrices[[i]][2,2]+matrices[[i]][3,2]
  lhtMPM$a2[i] <- matrices[[i]][3,2]/(matrices[[i]][2,2]+matrices[[i]][3,2])
}
lht[lht$Model=="IPM",] <- lhtIPM
lht[lht$Model=="MPM",] <- lhtMPM
```


Figures
```{r}
 Figure3a <- lht %>% 
  ggplot(aes(x=years))+
  geom_point(aes(y=s1,color=as.factor(Model)),show.legend = FALSE)+ 
  geom_line(aes(y=s1,color=as.factor(Model)),show.legend = FALSE)+
  scale_color_manual(values = c("IPM" = "red", "MPM" = "black"))+
  theme_bw(base_size = 6) +
  labs(x = "Year",
      y = "Survival",
      subtitle = "A- Seedling survival")
  
Figure3b <- lht %>% 
  ggplot(aes(x=years))+
  geom_point(aes(y=s2,color=as.factor(Model)),show.legend = FALSE)+ 
  geom_line(aes(y=s2,color=as.factor(Model)),show.legend = FALSE)+
  scale_color_manual(values = c("IPM" = "red", "MPM" = "black"))+
  theme_bw(base_size = 6) +
  labs(x = "Year",
      y = "Survival",
      subtitle = "B- Rosette survival")


Figure3c <- lht %>% 
  ggplot(aes(x=years))+
  geom_point(aes(y=a2,color=as.factor(Model)),show.legend = FALSE)+ 
  geom_line(aes(y=a2,color=as.factor(Model)),show.legend = FALSE)+
  scale_color_manual(values = c("IPM" = "red", "MPM" = "black"))+
  theme_bw(base_size = 6) +
  labs(x = "Year",
      y = "Flowering Probability",
      subtitle = "C- Flowering probability")


Figure3d <- lht %>% 
  ggplot(aes(x=years))+
  geom_point(aes(y=fs0,color=as.factor(Model)),show.legend = FALSE)+ 
  geom_line(aes(y=fs0,color=as.factor(Model)),show.legend = FALSE)+
  scale_color_manual(values = c("IPM" = "red", "MPM" = "black"))+
  theme_bw(base_size = 6) +
  labs(x = "Year",
      y = "Fecundity",
      subtitle = "D- Fecundity per flowering plant")

inset <- lht[lht$years<2015,] %>%
  ggplot(aes(x=years)) +
  geom_point(aes(y=fs0,color=as.factor(Model)),show.legend = FALSE)+ 
  geom_line(aes(y=fs0,color=as.factor(Model)),show.legend = FALSE) +
  scale_color_manual(values = c("IPM" = "red", "MPM" = "black")) +
  labs(x = "",
      y = "") +
  theme_bw(base_size = 6)


Figure3e <- ggplot(data=GrowthRateIPM, aes(x=Year, y=Lambda)) +
    geom_point(color="red", show.legend = FALSE) +
    geom_line(color="red", show.legend = FALSE) +
    geom_point(data=GrowthRateMPM, color="black", show.legend = FALSE) +
    geom_line(data=GrowthRateMPM, color="black", show.legend = FALSE) +
    annotate("segment", x = 1997, xend = 1999, y = 2.2, yend = 2.2,
           colour = "red", size = 0.5) +
    annotate("point", x=1998,y=2.2, colour="red", size=2)  +
   annotate("text", x = 2000, y = 2.2, label = "Integral Projection Model", hjust = 0) +
  annotate("segment", x = 1997, xend = 1999, y = 1.9, yend = 1.9,
           colour = "black", size = 0.5) +
  annotate("point", x=1998,y=1.9, colour="black", size=2)  +
  annotate("text", x = 2000, y = 1.9, label = "Matrix Projection Model", hjust = 0) +
    theme_bw(base_size = 6) +
    ylim(0,2.5)+
    labs(x = "Year",y = "Growth rate",
     subtitle="E- Global Population Growth rate")


library(patchwork)
Figure3d <- Figure3d +
  inset_element(inset, left = 0.01, bottom = 0.2, right = 0.60, top = 0.95)


cairo_ps("Figure_3.ps", onefile=TRUE, width=8.27, height = 11.69)
Figure3a + Figure3b  + Figure3c + Figure3d + Figure3e +
plot_layout(ncol=2, nrow=3)
dev.off()

```

Zoom sur le fs0

```{r}
i <- NULL
m <- NULL
for(k in 1:length(annees)){
  i[k] <- VitalRatesIPM[[k]][1,3] 
  m[k] <- matrices[[k]][1,3]
}

fs0 <- data.frame(anne)


plot(x=annees,i,ylim=c(0,30),type="l",col="red", xlab="Year", ylab="fs0")
lines(x=annees,m,col="black")
```
