---
title: "Validation with Flowering data"
author: "Loïc Pages & Eric Imbert"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  word_document: default
  html_document:
  df_print: paged
---

```{r}
rm(list=ls())
library(spaMM)
library(tidyverse)
library(popbio)

MatrixDim <- 50

spaMM.options(separation_max=70)
load("../../IPM/IPM_Kernal_Year.RData")
load("../../IPM/VitalRates.RData")

annees <- 1995:2021
populations <- c("E2","E1","Au","Po","Pe","Cr")

#Observed number of flowering plants
Nf <- c(494,420,604,638,343,490,631,482,815,435,613,794,210,NA,322,216,277,386,565,254,369,407,148,162,310,248,407,214)

#Flowering Probability
#Flowering function for The survival-growth kernel
flr0 <- function(x, a, Beta=0,Pop,year) {
  fake_data <- expand.grid(
  year = year,
  Pop = populations,
  Size0Mars = unique(x),
  Age = a)
  predi <- plogis(predict(Flowering, newdata = fake_data, allow.new.levels = T, type = "link") +  Beta)
  meanpredi <- aggregate(predi, list(fake_data$Size0Mars), mean)
  return(meanpredi$V1)
}

minsize <-  0.5
maxsize <-  25
maxsize1 <- 15
n.size <- MatrixDim
h <-  (maxsize - minsize) / n.size
h1 <-  (maxsize1 - minsize) / n.size
b = minsize + c(0:n.size) * h

#sizes for an individual of age a
#midpoint
ymid.a = 0.5 * (b[1:n.size] + b[2:(n.size + 1)])
#intervals
yI.a <- matrix(nrow = n.size, ncol = 2)
for (i in 1:n.size){
  yI.a[i,1] <- b[i]
  yI.a[i,2] <- b[i+1]
}

b1 = minsize + c(0:n.size) * h1
#sizes for an individual of age 1
#midpoint
ymid.1 = 0.5 * (b1[1:n.size] + b1[2:(n.size + 1)])
#intervals
yI.1 <- matrix(nrow = n.size, ncol = 2)
for (i in 1:n.size){
  yI.1[i,1] <- b1[i]
  yI.1[i,2] <- b1[i+1]
}
```

Number of observed flowering plants since 1995 with IPM
We predict the number of flowering plants by year starting by the
observed number of flowering plants the first year.

```{r,warning=FALSE}
N <- vector("double",length(annees)+1)
Nia <- array(data = 0, dim = c(length(annees), 8, MatrixDim))
Nf_est_IPM <- vector("double",length(annees)+1)

#distribution initiale en utilisant le kernel moyen
  A <- eigen.analysis(mean(IPMKernal_Year))
  W <- function(age) {return(A$stable.stage[(50 * (age - 1) + 1):(50 * age)])}
  Nf_dens <- sum(W(1) * flr0(ymid.1, 1, year=1995)) 
  for (a in 2:8) {
    Nf_dens <- Nf_dens + sum(W(a) * flr0(ymid.a, a, year=1995))
  }
  
# Nombre d'individus total la première année, utilisant les données observées
  N[1] <- Nf[1] / Nf_dens
  # Nombre d'individus dans chaque classe de taille et d'age
  for (a in 1:8) {
    for (i in 1:MatrixDim) {
      Nia[1, a, ] <- N[1] * W(a)
    }
  }
  
  Nf_est_IPM[1] <- Nf[1]

  # Itération sur les années suivantes
  for (yr in 2:length(annees)) {
    year <- annees[yr-1]
    A <- eigen.analysis(IPMKernal_Year[[yr-1]])
    Fec <- function(a) {
      #a age de plante mère
      return(IPMKernal_Year[[yr-1]][1:50, ((a - 1) * 50 + 1):(a * 50)])
    }
    P <- function(a) {
      #a age de plante à t
      if (a == 8) {
        return(IPMKernal_Year[[yr-1]][((50*(a-1))+1):(50*a), (50*(a-1)+1):(50*a)])
        }
      return(IPMKernal_Year[[yr-1]][((50*a)+1):(50*(a+1)), (50*(a-1)+1):(50*a)])}
   
    # Calcul du nombre d'individus dans chaque classe de taille et d'age en utilisant le kernel
    for (a in 1:8) { # Nouvelles plantules produites
      Nia[yr, 1, ] <- Nia[yr, 1, ] + Fec(a) %*% Nia[yr-1, a, ]
    }
    for (a in 2:8) { # Croissance-survie des plantes
      Nia[yr, a, ] <- P(a) %*% Nia[yr-1, a - 1, ]
    }
    Nia[yr, 8, ] <- Nia[yr, 8, ] + P(8) %*% Nia[yr-1, 8, ]
    
    #Calcul du nombre de plantes en fleurs
    Nf_est_IPM[yr] <- sum(Nia[yr, 1, ] * flr0(ymid.1, 1, year=year))
    for (a in 2:8) {
      Nf_est_IPM[yr] <- Nf_est_IPM[yr] + sum(Nia[yr, a, ] * flr0(ymid.a, a, year=year))
    }
  }
  
#derniere annnee  
    year <- 2021
    yr <- 27
    A <- eigen.analysis(IPMKernal_Year[[yr]])
    Fec <- function(a) {
      #a age de plante mère
      return(IPMKernal_Year[[yr]][1:50, ((a - 1) * 50 + 1):(a * 50)])
    }
    P <- function(a) {
      #a age de plante à t
      if (a == 8) {
        return(IPMKernal_Year[[yr]][((50*(a-1))+1):(50*a), (50*(a-1)+1):(50*a)])
        }
      return(IPMKernal_Year[[yr]][((50*a)+1):(50*(a+1)), (50*(a-1)+1):(50*a)])}
   
    # Calcul du nombre d'individus dans chaque classe de taille et d'age en utilisant le kernel
    for (a in 1:8) { # Nouvelles plantules produites
      Nia[yr, 1, ] <- Nia[yr, 1, ] + Fec(a) %*% Nia[yr-1, a, ]
    }
    for (a in 2:8) { # Croissance-survie des plantes
      Nia[yr, a, ] <- P(a) %*% Nia[yr-1, a - 1, ]
    }
    Nia[yr, 8, ] <- Nia[yr, 8, ] + P(8) %*% Nia[yr-1, 8, ]
    
    #Calcul du nombre de plantes en fleurs
    Nf_est_IPM[yr] <- sum(Nia[yr, 1, ] * flr0(ymid.1, 1, year=year))
    for (a in 2:8) {
      Nf_est_IPM[yr] <- Nf_est_IPM[yr] + sum(Nia[yr, a, ] * flr0(ymid.a, a, year=year))
    }
  
```


Estimated number of flowering plants by years

```{r}
plot(y=Nf_est_IPM, x=c(annees,2022), type="l", ylim=c(0,max(c(Nf_est_IPM,Nf),na.rm=TRUE)), xlab="Year", ylab="Number of flowering plants")
lines(y=Nf, x=c(annees,2022), col="red")
text(2015,600, "Red line = Observed data")
text(2015,700, "Black line = Predicted data with IPM")

```
With MPM
```{r}
load("../MPM/matricesperyear.RData")

Nf_est_MPM <- NA

# Définition de la matrice initiale et du vecteur propre
M <- mean(matrices)  # on prend avec la matrice moyenne pour définir la structure t=0
ev <- eigen(M)
W <- abs(Re(ev$vectors[,1]))
W <- W/sum(W)
N <- round(W*Nf[1]/W[3])
Nf_est_MPM[1] <- Nf[1]
    
for (i in 2:28){
  M <- matrices[[i-1]]
  ev <- eigen(M)
  W <- abs(Re(ev$vectors[,1]))
  W <- W/sum(W)
  N <- M%*%N
  Nf_est_MPM[i] <- N[3]
  }
```

```{r}
plot(y=Nf_est_MPM, x=c(annees,2022), type="l", ylim=c(0,max(c(Nf_est_MPM, Nf),na.rm=TRUE)), xlab="Year", ylab="Number of flowering plants")
lines(y=Nf, x=c(annees,2022), col="red")
text(2015,600, "Red line = Observed data")
text(2015,700, "Black line = Predicted data with IPM")
```

Nf_est_IPM versus Nf_est_MPM
```{r,warning=FALSE}
plot(Nf_est_IPM, Nf_est_MPM, xlim=c(0,800), ylim=c(0,800),
     xlab="Nb flowering plants from IPM", ylab="Nb of flowering plants from MPM")
abline(a=0,b=1)
```






Comparaison des variations interannuelles

```{r}
observed_ratio <- Nf[-1]/Nf[-28]
ratio_IPM <- Nf_est_IPM[-1]/Nf_est_IPM[-28]
ratio_MPM <- Nf_est_MPM[-1]/Nf_est_MPM[-28]

ratio_max <- max(observed_ratio, ratio_IPM,ratio_MPM, na.rm=TRUE)

plot(observed_ratio ~ annees, ylim=c(0,ratio_max), xlab="Year", ylab="Observed ratio", type="l", col="red")
lines(ratio_IPM ~ annees, col="green")
lines(ratio_MPM ~ annees, col="blue")
text(2000,3, "Red line = observed ratio")
text(2000,3.5, "green line = IPM")
text(2000,4, "blue line = MPM")

```
```{r}
plot(observed_ratio, ratio_IPM, xlim=c(0,ratio_max), ylim=c(0,ratio_max),
     xlab="Observed ratio", ylab="Ratio using the prediction", col="green")
points(observed_ratio, ratio_MPM, col="blue")
abline(a=0,b=1)
text(3,1,"Blue = MPM")
text(3,2,"Green = IPM")


```


