---
title: "Asymptotic and stochastic Lambdas for IPM"
author: "Eric Imbert"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

Import kernal per population and per year => IPM_Kernal_Pop_Year.RData
Import global kernal per population => IPM_Kernal_Pop.RData
Will be used to define the initial distribution for each population


```{r setup, include=FALSE}
rm(list=ls())
library(splines)
library(tidyverse)
library(spaMM)
spaMM.options(separation_max=70)
library(popbio)

#Load the kernel 
load("IPM_Kernal_Pop_Year.RData")
load("IPM_Kernal_Pop.RData")

populations <- c("Po","Au","Pe","E1","E2","Cr")
annees <- 1:26
```


```{r}
ME2 <- list();ME1 <- list();MAu <- list();MPo <- list();MPe <- list();MCr <- list()

for (i in 1:27){
MPo[[i]] <- IPMKernalPopYear[[i]]; 
MAu[[i]] <- IPMKernalPopYear[[i+27]]
MPe[[i]] <- IPMKernalPopYear[[i+27*2]]
ME1[[i]] <- IPMKernalPopYear[[i+27*3]]
ME2[[i]] <- IPMKernalPopYear[[i+27*4]]
MCr[[i]] <- IPMKernalPopYear[[i+27*5]]
}
MPo <- MPo[-1] #remove year=1995
MAu <- MAu[-1]
MPe <- MPe[-1]
ME1 <- ME1[-1]
ME2 <- ME2[-1]
MCr <- MCr[-1]

#Asymptotic value per populations

for (p in 1:length(populations)) {
  # Initialisation
  Pop <- populations[p]
  lambdaA <- NULL
  if (Pop=="E2") {matrices <- ME2}
  if (Pop=="E1") {matrices <- ME1}
  if (Pop=="Au") {matrices <- MAu}
  if (Pop=="Po") {matrices <- MPo}
  if (Pop=="Pe") {matrices <- MPe}
  if (Pop=="Cr") {matrices <- MCr}

  for (year in annees)
  {lambdaA[year] <- eigen.analysis(matrices[[year]])$lambda}
  
  cat("Population=",Pop,"Mean LamdaA=", mean(lambdaA),
        "Min=", min(lambdaA),"Max=", max(lambdaA), "\n")
  
}

```

```{r}

lambdaS <- NULL
lambdaSPo <- NULL
lambdaSAu <- NULL
lambdaSPe <- NULL
lambdaSE1 <- NULL
lambdaSE2 <- NULL
lambdaSCr <- NULL






for (p in 1:length(populations)) {
  # Initialisation
  Pop <- populations[p]
  
  if (Pop=="E2") {matrices <- ME2;A <- eigen.analysis(IPMKernal_Pop$E2)}
  if (Pop=="E1") {matrices <- ME1;A <- eigen.analysis(IPMKernal_Pop$E1)}
  if (Pop=="Au") {matrices <- MAu;A <- eigen.analysis(IPMKernal_Pop$Au)}
  if (Pop=="Po") {matrices <- MPo;A <- eigen.analysis(IPMKernal_Pop$Po)}
  if (Pop=="Pe") {matrices <- MPe;A <- eigen.analysis(IPMKernal_Pop$Pe)}
  if (Pop=="Cr") {matrices <- MCr;A <- eigen.analysis(IPMKernal_Pop$Cr)}

 #Initial distribution using mean kernal
  N0 <- A$stable.stage

  #1000 iterations
    for (iter in 1:1000) {
       # Iteration over 100 years
            for (time in 1:100) {
               yr <- sample(annees,1)
               Nt <-matrices[[yr]] %*% N0 
               lambdaS[time] <- log(sum(Nt))
               N0 <- Nt/sum(Nt)
                            }
  if (Pop=="E2") {lambdaSE2[iter] <- exp(mean(lambdaS))}
  if (Pop=="E1") {lambdaSE1[iter] <- exp(mean(lambdaS))}
  if (Pop=="Au") {lambdaSAu[iter] <- exp(mean(lambdaS))}
  if (Pop=="Po") {lambdaSPo[iter] <- exp(mean(lambdaS))}
  if (Pop=="Pe") {lambdaSPe[iter] <- exp(mean(lambdaS))}
  if (Pop=="Cr") {lambdaSCr[iter] <- exp(mean(lambdaS))}                              } #end of iterations
    
} #end of populations


mean(lambdaSE2);mean(lambdaSE2)-1.96*sd(lambdaSE2);mean(lambdaSE2)+1.96*sd(lambdaSE2);
mean(lambdaSE1);mean(lambdaSE1)-1.96*sd(lambdaSE1);mean(lambdaSE1)+1.96*sd(lambdaSE1);
mean(lambdaSAu);mean(lambdaSAu)-1.96*sd(lambdaSAu);mean(lambdaSAu)+1.96*sd(lambdaSAu);
mean(lambdaSPo);mean(lambdaSPo)-1.96*sd(lambdaSPo);mean(lambdaSPo)+1.96*sd(lambdaSPo);
mean(lambdaSPe);mean(lambdaSPe)-1.96*sd(lambdaSPe);mean(lambdaSPe)+1.96*sd(lambdaSPe);
mean(lambdaSCr);mean(lambdaSCr)-1.96*sd(lambdaSCr);mean(lambdaSCr)+1.96*sd(lambdaSCr)
```

