---
title: "Fecundity Models Fitted"
author: "Loïc Pages & Eric Imbert"
date: "`r Sys.Date()`"
output:
  pdf_document: default
word_document: default
html_document:
  df_print: paged
---
  
Plot raw data and predicted values from models (see ModelSelection.Rmd) for fecundity (number of capitula) => Only one model


```{r}
rm(list=ls())
library(knitr)
library(spaMM)
library(tidyverse)
library(splines)
library(foreach)
library(doParallel)
library(patchwork)

IPM_data <- read.csv("../data/donneesIPM.csv")
centauree_data <- IPM_data[!is.na(IPM_data$Size0Mars) & !is.na(IPM_data$Age),]
centauree_data$Age[centauree_data$Age > 8] <- 8

spaMM.options(separation_max=70)
load("SelectedModels.RData")

#fake data

annees <- 1995:2022
populations <- c("E2","E1","Au","Po","Pe","Cr")
taille_range <- seq(0.5, 25, by = 0.5) 
age_range <- 1:8

fake_data <- expand.grid(
  year = annees,
  Pop = populations,
  Size0Mars = taille_range,
  Age = age_range
)

fake_data <- fake_data %>% 
  mutate(Nrw = row_number())
```



```{r}
cptldata <- centauree_data[centauree_data$Flowering!=0,]

```

Nombre de capitules moyen / age


```{r, warning=FALSE}
capidata <- cptldata %>% 
  group_by(Age) %>% 
  mutate(meancptl=mean(Capitule)) 
capidata%>% 
  ggplot(aes(x = Age, y = meancptl)) +
  geom_count(aes(y=Capitule), alpha=0.6) +
  labs(title = "Relation entre l'age et le nombre de capitules",
       x = "Age",
       y = "Nombre de capitules") +
  theme_minimal()

#Nombre de capitule / taille 
cptldata %>% 
  
  ggplot(aes(x=Size0Mars,y=Capitule))+
  geom_point() +
  labs(title = "Relation entre la taille et le nombre de capitules",
       x = "taille",
       y = "Nombre de capitules") +
  theme_minimal()

# Nombre de capitule / année 
cptldata %>% 
  ggplot(aes(x=year,y=Capitule))+
  geom_point() +
  labs(title = "Relation entre l'année et le nombre de capitules",
       x = "année",
       y = "Nombre de capitules") +
  theme_minimal()
```

```{r}
summary(Cptlglm1)
```

```{r,results='hide'}
Cptlpredict <- predict(Cptlglm1, newdata = fake_data)[,1]
```


```{r}
plot_capitule <- function(data = fake_data, prediction, var, fact) {
  data %>%
    mutate(cptl_predi = exp(prediction)) %>%
    group_by(!!sym(var),!!sym(fact)) %>% 
    summarise(cptl_predi = mean(cptl_predi)) %>%
    ggplot(aes(x = .data[[var]], y = cptl_predi)) +
    geom_point(data = cptldata, aes(y = Capitule), alpha=0.6)+
    geom_line(aes(color = as.factor(.data[[fact]])),show.legend = FALSE) +
    theme_minimal() +
    ylim(0,100)
}

plot_capitule2 <- function(data = fake_data, prediction, var, fact) {
  data %>%
    mutate(cptl_predi = exp(prediction)) %>%
    group_by(!!sym(var),!!sym(fact)) %>% 
    summarise(cptl_predi = mean(cptl_predi)) %>%
    ggplot(aes(x = .data[[var]], y = cptl_predi)) +
    geom_point(data = cptldata, aes(y = Capitule), alpha=0.6)+
    geom_line(aes(color = as.factor(.data[[fact]])),show.legend = FALSE) +
    theme_minimal() +
    scale_color_viridis_d(option = "plasma")+
    ylim(0,100)
}
```


Nombre de capitules en fonction de la taille

Effet année

```{r,warning=FALSE,echo=FALSE,message=FALSE}
var <- "Size0Mars"
fact <- "year"

wrap_plots(plot_capitule(prediction = Cptlpredict, var=var, fact=fact))
```

Nombre de capitules en fonction de l'age

En fixant la population : voir l'effet année
```{r,warning=FALSE, echo=FALSE,message=FALSE}
var <- "Age"
fact <- "year"

wrap_plots(plot_capitule(prediction = Cptlpredict, var=var, fact=fact))
```
```{r}
gof(Cptlglm1)
```

